### ISSUE TITLE
Add Capacitor 6 support

### ISSUE THREAD

**Issue by pormel** [harmonwood/capacitor-video-player#154]
Please, add support for Capacitor 6
Thanks !

**Comment by marcjulian** [comment]
Capacitor provides a migration script `npx @capacitor/plugin-migration-v5-to-v6@latest` updating the files automatically.

https://capacitorjs.com/docs/updating/plugins/6-0#using-capacitorplugin-migration-v5-to-v6

**Comment by marcjulian** [comment]
No worries. Thanks for the plugin anyways.

**Comment by ivancduran** [comment]
Hi @jepiqueau, please before upgrading to version 6, could you please review the pull request I made to add DRM support to the native players. I also tried to contact you, because I need to develop a number of features over the video player and I want to check with you how we can collaborate.

I already sent you and email explaning the situation.

Thanks you very much for your time and for this awesome plugin.

**Comment by WardPearce** [comment]
This fork exists, can't say if it works or not tho

https://github.com/Jiwoks/capacitor-video-player

**Comment by harmonwood** [comment]
Hello, all,
I have been granted new maintainer of this project.
As an update, Capacitor 6 support will be my main priority, second of course to looking at outstanding PR's. (@ivancduran)
Please, bear with me as I get my legs for this project.

**Comment by eduardoRoth** [comment]
@harmonwood I created a PR for the update to Capacitor v6 (https://github.com/harmonwood/capacitor-video-player/pull/164)

I also have two other PRs for fixes that I found while using this plugin with a client project.
- https://github.com/harmonwood/capacitor-video-player/pull/162
- https://github.com/harmonwood/capacitor-video-player/pull/163

**Comment by eduardoRoth** [comment]
@harmonwood , let me know if you need something else in the PRs, so I can work on that and we could merge them to `master`

Thank you! 😄

**Comment by harmonwood** [comment]
version 6.0.0 has been published to npm
